config/routes.rb
Rails.application.routes.draw do
  root 'pages#home'
  devise_for :users, controllers: {
    registrations: 'users/registrations',
    sessions: 'users/sessions'
  }

  get 'domains/new/:name' => 'domains#new'
  resources :domains, param: :name, constraints: { name: /[0-z\.]+/ }
end

app/models/domain.rb
class Domain < ActiveRecord::Base
  belongs_to :user

  has_many :collaborations
  has_many :collaborators, through: :collaborations, source: :user

  has_many :nameservers
  has_many :glue

  has_one :owner
  has_one :admin
  has_one :billing
  has_one :tech

  validates_associated :owner
  validates_associated :admin
  validates_associated :billing
  validates_associated :tech

  after_initialize do |domain|
    if domain.new_record?
      domain.build_owner
      domain.build_admin
      domain.build_billing
      domain.build_tech
    end
  end

  # def initialize(params={})
  #   self.collaborators = []
  # end

  def to_param
    self.name
  end

  def to_xml(options = {})
    super include: [ :owner, :admin, :billing, :tech, :nameservers ]
  end

  def as_json(options = {})
    super include: [ :owner, :admin, :billing, :tech, :nameservers ]
  end
end

app/controllers/domains_controller.rb
class DomainsController < ApplicationController
  before_action :set_domain, only: [:show, :edit, :update, :destroy]

  def index
    # get_all_domains.each { |d| Domain.find_or_create_by(name: d['name']) }
    @domains = current_user.domains
  end

  def show
    api_query_results = get_domain(params[:name])
    if api_query_results.success?
      @domain.epp = get_epp_code(@domain) if @domain.epp.nil? || @domain.epp.empty?
      response = api_query_results.response['attributes']

      @domain.autorenew = response['let_expire']
      @domain.privacy = get_privacy_status(@domain)
      @domain.lock = get_lock_status(@domain)

      nameservers = response['nameserver_list']
      nameservers.each do |ns|
        Nameserver.find_or_create_by(order: ns['sortorder'], domain: @domain) do |nameserver|
          nameserver.name = ns['name']
        end
      end
      @domain.nameservers.where.not(order: [1..nameservers.count]).destroy_all

      @domain.registration = DateTime.parse(response['registry_createdate'])
      @domain.expiry = DateTime.parse(response['registry_expiredate'])

      contacts = response['contact_set']
      @domain.owner.from_json(contacts['owner'])
      @domain.admin.from_json(contacts['admin'])
      @domain.billing.from_json(contacts['billing'])
      @domain.tech.from_json(contacts['tech'])

      @domain.save
      render :show
    else
      @domain_name = params[:name]
      if domain_available?(@domain_name)
        redirect_to new_domain_path(name: @domain_name)
      else
        render :unavailable
      end
    end
  end

  def new
    @domain = Domain.new

    if params[:name]
      @domain.name = params[:name]
    else
      @domain.name = Faker::Internet.domain_word + ".com"
    end

    render :unavailable unless domain_available?(@domain.name)

    registration_params = current_user.profile.serializable_hash
    registration_params.delete('user_id')

    @domain.owner     = Owner.new(registration_params)
    @domain.admin     = Admin.new(registration_params)
    @domain.billing   = Billing.new(registration_params)
    @domain.tech      = Tech.new(registration_params)
  end

  def edit
  end

  def create
    @domain = Domain.new(domain_params)

    @domain.owner   = Owner.new contact_params "owner"
    @domain.admin   = Admin.new contact_params "admin"
    @domain.billing = Billing.new contact_params "billing"
    @domain.tech    = Tech.new contact_params "tech"

    if @domain.valid?
      registration = register(@domain)
      response = registration.response['response_text']
      if registration.success?
        @domain.epp = get_epp_code @domain
        @domain.save
        redirect_to domain_url(@domain), notice: response
      else
        render :new, alert: response
      end
    else
      render :new
    end

  end

  def update
    if @domain.update(domain_params)
      redirect_to @domain, notice: 'Domain was successfully updated.'
    else
      render :edit
    end
  end

  def destroy
    @domain.destroy
    redirect_to domains_url, notice: 'Domain was successfully destroyed.'
  end

  def unavailable
    @domain_name = params[:name]
  end

  private
    def set_domain
      @domain = Domain.find_by(name: params[:name])
    end

    def domain_params
      params.require(:domain).permit(:name, :lock, :privacy, :epp)
    end

    def get_domain(name)
      server.call(
        action: 'get',
        object: 'domain',
        attributes: {
          domain: name,
          type: 'all_info'
        }
      )
    end

    def contact_params(type)
      params
        .require(type.underscore.to_sym)
        .permit(:organization, :first_name, :last_name, :address1, :address2, :address3,
          :city, :state, :country, :postal_code, :email, :phone_number, :type)
    end

    def register(domain)
      response = server.call(
        action:                 'sw_register',
        object:                 'domain',
        attributes: {
          auto_renew:           '1',
          contact_set: {
            owner:              domain.owner.as_json,
            admin:              domain.admin.as_json,
            billing:            domain.billing.as_json,
            tech:               domain.tech.as_json
          },
          custom_nameservers:   '0',
          custom_tech_contact:  '1',
          dns_template:         '*blank*',
          domain:               domain.name,
          f_lock_domain:        domain.lock ? '1' : '0',
          f_whois_privacy:      domain.privacy ? '1' : '0',
          period:               '1',
          reg_username:         'example',
          reg_password:         'example123',
        }
      )
    end

    def get_epp_code(domain)
      query = server.call(
        action: 'get',
        object: 'domain',
        attributes: { domain: domain.name, type: 'domain_auth_info' }
      )
      query.response['attributes']['domain_auth_info']
    end

    def get_privacy_status(domain)
      query = server.call(
        action: 'get',
        object: 'domain',
        attributes: { domain: domain.name, type: 'whois_privacy_state' }
      )
      query.response['attributes']['state'] === "enabled"
    end

    def get_lock_status(domain)
      query = server.call(
        action: 'get',
        object: 'domain',
        attributes: { domain: domain.name, type: 'status' }
      )
      query.response['attributes']['lock_state'] === "1"
    end

    def get_all_domains
      min_expiry = Date.today
      max_expiry = min_expiry + 10.years
      query = server.call(
        action: 'get_domains_by_expiredate',
        object: 'domain',
        attributes: {
          exp_to: max_expiry.strftime("%Y-%m-%d"),
          exp_from: min_expiry.strftime("%Y-%m-%d"),
          state: 'active'
        }
      )
      query.response['attributes']['exp_domains']
    end

    def domain_available?(name)
      query = server.call(
        action: 'lookup',
        object: 'domain',
        attributes: {
          domain: name
        }
      )
      query.response['response_code'] == "210"
    end
end

app/helpers/domains_helper.rb
module DomainsHelper
end

app/views/domains/_form.html.erb
<%= form_for @domain do |domain| %>
  <div class="actions">
    <div class="text field">
      <%= domain.label :name, "Domain Name" %>
      <%= domain.text_field :name %>
    </div>

    <div class="radio field">
      Transfer Lock
      <%= domain.radio_button :lock, true %>
      <%= domain.label :lock_true, "Enabled" %>
      <%= domain.radio_button :lock, false %>
      <%= domain.label :lock_false, "Disabled" %>
    </div>

    <div class="radio field">
      WHOIS Privacy
      <%= domain.radio_button :privacy, true %>
      <%= domain.label :privacy_true, "Enabled" %>
      <%= domain.radio_button :privacy, false %>
      <%= domain.label :privacy_false, "Disabled" %>
    </div>

    <div class="whois owner">
      <%= fields_for @domain.owner do |owner| %>
        <h2>Owner</h2>
        <%= render 'whois_form', whois: owner %>
      <% end %>
    </div>

    <div class="whois admin">
      <%= fields_for @domain.admin do |admin| %>
        <h2>Administrator</h2>
        <%= render 'whois_form', whois: admin %>
      <% end %>
    </div>

    <div class="whois billing">
      <%= fields_for @domain.billing do |billing| %>
        <h2>Billing</h2>
        <%= render 'whois_form', whois: billing %>
      <% end %>
    </div>

    <div class="whois tech">
      <%= fields_for @domain.tech do |tech| %>
        <h2>Technical</h2>
        <%= render 'whois_form', whois: tech %>
      <% end %>
    </div>

    <div class="button field">
      <%= domain.button %>
    </div>
  </div>
<% end %>

app/views/domains/_validation.html.erb
<div class="error"><%= message %></div>

app/views/domains/_whois.html.erb
<div class="text field">
  <%= whois.label :organization, "Organization" %>
  <%= whois.text_field :organization, autocomplete: false %>
</div>

<div class="text field">
  <%= whois.label :last_name, "Last name" %>
  <%= whois.text_field :last_name, autocomplete: false %>
</div>

<div class="text field">
  <%= whois.label :first_name, "First name" %>
  <%= whois.text_field :first_name, autocomplete: false %>
</div>

<div class="text field">
  <%= whois.label :address1, "Address" %>
  <%= whois.text_field :address1, autocomplete: false %>
</div>

<div class="text field">
  <%= whois.label :address2, "Address 2" %>
  <%= whois.text_field :address2, autocomplete: false %>
</div>

<div class="text field">
  <%= whois.label :address3, "Address 3" %>
  <%= whois.text_field :address3, autocomplete: false %>
</div>

<div class="text field">
  <%= whois.label :city, "City" %>
  <%= whois.text_field :city, autocomplete: false %>
</div>

<div class="text field">
  <%= whois.label :state, "State" %>
  <%= whois.text_field :state, autocomplete: false %>
</div>

<div class="text field">
  <%= whois.label :country, "Country" %>
  <%= whois.text_field :country, autocomplete: false %>
</div>

<div class="text field">
  <%= whois.label :postal_code, "Postal code" %>
  <%= whois.text_field :postal_code, autocomplete: false %>
</div>

<div class="text field">
  <%= whois.label :email, "Email" %>
  <%= whois.email_field :email %>
</div>

<div class="text field">
  <%= whois.label :phone_number, "Phone number" %>
  <%= whois.telephone_field :phone_number %>
</div>

app/views/domains/_whois_form.html.erb
<div class="text field">
  <%= whois.label :organization, "Organization" %>
  <%= whois.text_field :organization, autocomplete: false %>
</div>

<div class="text field">
  <%= whois.label :last_name, "Last name" %>
  <%= whois.text_field :last_name, autocomplete: false %>
</div>

<div class="text field">
  <%= whois.label :first_name, "First name" %>
  <%= whois.text_field :first_name, autocomplete: false %>
</div>

<div class="text field">
  <%= whois.label :address1, "Address" %>
  <%= whois.text_field :address1, autocomplete: false %>
</div>

<div class="text field">
  <%= whois.label :address2, "Address 2" %>
  <%= whois.text_field :address2, autocomplete: false %>
</div>

<div class="text field">
  <%= whois.label :address3, "Address 3" %>
  <%= whois.text_field :address3, autocomplete: false %>
</div>

<div class="text field">
  <%= whois.label :city, "City" %>
  <%= whois.text_field :city, autocomplete: false %>
</div>

<div class="text field">
  <%= whois.label :state, "State" %>
  <%= whois.text_field :state, autocomplete: false %>
</div>

<div class="text field">
  <%= whois.label :country, "Country" %>
  <%= whois.text_field :country, autocomplete: false %>
</div>

<div class="text field">
  <%= whois.label :postal_code, "Postal code" %>
  <%= whois.text_field :postal_code, autocomplete: false %>
</div>

<div class="text field">
  <%= whois.label :email, "Email" %>
  <%= whois.email_field :email %>
</div>

<div class="text field">
  <%= whois.label :phone_number, "Phone number" %>
  <%= whois.telephone_field :phone_number %>
</div>

app/views/domains/_whois_record.html.erb
<h3><%= title %></h3>
<ul class="whois">
  <li>
    <%= contact.organization %>
  </li>
  <li>
    <%= contact.first_name %> <%= contact.last_name %>
  </li>
  <li>
    <%= contact.address1 %>,
    <%= contact.address2 %>
  </li>
  <li>
    <%= contact.city %>,
    <%= contact.state %>,
    <%= contact.country %>.
    <%= contact.postal_code %>
  </li>
  <li>
    <%= contact.phone_number %>
  </li>
</ul>

app/views/domains/edit.html.erb
<h1>Editing Domain</h1>

<%= render 'form' %>

<%= link_to 'Show', @domain %> |
<%= link_to 'Back', domains_path %>

app/views/domains/index.html.erb
<h1>Domains</h1>

<hr>

<ul>
  <% @domains.order(:registration).each do |domain| %>
    <li><%= link_to domain.name, domain %></li>
  <% end %>
</ul>

<hr>

<%= link_to 'New Domain', new_domain_path %>

app/views/domains/new.html.erb
<div class="register domain">
  <h1>Register Domain Name</h1>

  <%= link_to 'View all domains', domains_path %>

  <% if @domain.errors.any? %>
    <div class="errors">
      <%= render partial: 'validation', collection: @domain.errors.full_messages, as: 'message' %>

      <% unless @domain.owner.valid? %>
        <%= render partial: 'validation', collection: @domain.owner.errors.full_messages, as: 'message' %>
      <% end %>

      <% unless @domain.admin.valid? %>
        <%= render partial: 'validation', collection: @domain.admin.errors.full_messages, as: 'message' %>
      <% end %>

      <% unless @domain.billing.valid? %>
        <%= render partial: 'validation', collection: @domain.billing.errors.full_messages, as: 'message' %>
      <% end %>

      <% unless @domain.tech.valid? %>
        <%= render partial: 'validation', collection: @domain.tech.errors.full_messages, as: 'message' %>
      <% end %>
    </div>
  <% end %>

  <%= render 'form' %>
</div>

app/views/domains/show.html.erb
<div class="show domain">
  <h1><%= @domain.name %></h1>

  <ul class="properties">
    <li>
      <h2>Auto Renew</h2>
      <div class="autorenew">
        <%= @domain.autorenew ? "Yes" : "No" %>
      </div>
    </li>
    <li>
      <h2>Registration Date</h2>
      <div class="registration">
        <%= @domain.registration.strftime('%B %d, %Y') %>
      </div>
    </li>
    <li>
      <h2>Expiry Date</h2>
      <div class="expiry">
        <%= @domain.expiry.strftime('%B %d, %Y') %>
      </div>
    </li>
    <li>
      <h2>Transfer Lock</h2>
      <div class="lock">
        <%= @domain.lock ? "On" : "Off" %>
      </div>
    </li>
    <li>
      <h2>WHOIS Privacy</h2>
      <div class="privacy">
        <%= @domain.privacy ? "On" : "Off" %>
      </div>
    </li>
    <li>
      <h2>Authorization Code</h2>
      <div class="epp">
        <pre><%= @domain.epp %></pre>
      </div>
    </li>
    <li>
      <h2>Nameservers</h2>
      <ul class="nameservers">
        <% @domain.nameservers.order(:order).each do |ns| %>
          <li><%= ns.name %></li>
        <% end %>
      </ul>
    </li>
    <li>
      <h2>Registration Records</h2>
      <div class="records">
        <%= render partial: 'whois_record', locals: { title: 'Owner', contact: @domain.owner } %>
        <%= render partial: 'whois_record', locals: { title: 'Administrator', contact: @domain.admin } %>
        <%= render partial: 'whois_record', locals: { title: 'Billing', contact: @domain.billing } %>
        <%= render partial: 'whois_record', locals: { title: 'Technical', contact: @domain.tech } %>
      </div>
    </li>
  </ul>
</div>

app/views/domains/unavailable.html.erb
<div class="unavailable">
  <%= @domain.name %> is not available</h1>
</div>